default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] + "_development" %>

test:
  <<: *default
  database: <%= ENV["DB_NAME"] + "_test" %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["DB_NAME"] + "_production" %>
  cache:
    <<: *primary_production
    database: <%= ENV["DB_NAME"] + "_production_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV["DB_NAME"] + "_production_queue" %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV["DB_NAME"] + "_production_cable" %>
    migrations_paths: db/cable_migrate
