---
services:
  new_app-db:
    image: postgres
    container_name: new_app-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
  new_app-app:
    build: .
    container_name: new_app-app
    env_file: .env
    environment:
      - DB_HOST=new_app-db
    volumes:
      - ~/.ssh/id_rsa:/home/rails/.ssh/id_rsa 
      - ~/.ssh/id_rsa.pub:/home/rails/.ssh/id_rsa.pub
      - ./.gem:/home/rails/.gem
    ports:
      - $PORT:$PORT
    stop_grace_period: 2s
    tty: true
    command: bin/dev
...
