---
services:
  db:
    image: postgres
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data
      
  app:
    build: .
    container_name: app
    env_file: .env
    environment:
      - DB_HOST=db
    ports:
      - $PORT:$PORT
    volumes:
      - ~/.ssh/id_rsa:/home/rails/.ssh/id_rsa 
      - ~/.ssh/id_rsa.pub:/home/rails/.ssh/id_rsa.pub
      - ./:/rails_root
    stop_grace_period: 2s
    tty: true
    command: bin/dev
...
